workflows:
  hello-world:
    name: Fetch Pipeline
    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up"
    publishing:
      email:
        recipients:
          - bobzhong64@gmail.com
      
