workflows:
  hello-world:
    name: Fetch Pipeline
    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up"
      - name: Build the .app
        script: | 
          # build using workspace
          xcodebuild build \
            -workspace "Fetch-Coding-Challenge.xcworkspace" \
            -scheme "Fetch-Coding-Challenge" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
        
    publishing:
      email:
        recipients:
          - bobzhong64@gmail.com
      
